customers:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/customers_db?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
      username: accounts_db
      password: accounts_db123
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
  allow-get-customers: true
  server:
    port: 7070
eureka:
  client:
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/: