

#accounts
accounts:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/accounts_db?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
      username: accounts_db
      password: accounts_db123
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
  allow-get-accounts: false
  server:
    port: 7777

#customers
customers:
   spring:
     datasource:
       url: jdbc:mysql://localhost:3306/customers_db?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
       username: accounts_db
       password: accounts_db123
     jpa:
       database: mysql
       show-sql: true
       hibernate:
         ddl-auto: update
   server:
     port: 7070