server:
  port: 7777
accounts:
    datasource:
      url: jdbc:mysql://localhost:3306/accounts_db?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
      username: accounts_db
      password: accounts_db123